### ISSUE TITLE
Add mousescroll

### ISSUE THREAD

**Issue by kartikluke** [kirkas/Ascensor.js#36]
I'm not up to date on the latest changes but I think mouse scrolling should be integrated into Ascensor. At the moment I use a plugin to call the Ascensor next()/previous() method depending on the direction one is scrolling in.

It is the natural way in which people expect to interact with the website. A lot of users get confused with the layout especially if it's a simple vertical layout.

**Comment by devdanwallace** [comment]
Anyone solved the scroll problem? Thanks.

**Comment by pooyaa** [comment]
Hello dear friend.
It is a good decision.
Does Firefox have been fixed?
It's great that you are attempting to update it.
Thank you very much.

I'm testing soon.

**Comment by pooyaa** [comment]
Wow this is great.
It is compatible with all devices.
Thank you.
