### ISSUE TITLE
Wow! Wow! and WOW!!!

### ISSUE THREAD

**Issue by trinione** [kirkas/Ascensor.js#41]
This has been a wonderful experience using and watching this project grow and grow to such a top level.

I noticed the site was offline a few months aback and I just came back to get some info and was pleasantly surprised to see the new site and logo. GREAT STUFF!! :)

Just 2 things I noted:

1) Two minor typos:
#Home: It work with >> It works with... (missing the 's' in works)
and
#Donate: here's and ugly button >> here's an ugly button (should be 'an', not 'and')

2) On the #Doc page, can you include the text 'Scroll down on the Github page for usage instructions' or something like that.

Again, great work!

Regards,
Trinione

**Comment by kirkas** [comment]
thanks! fixed!
