### ISSUE TITLE
Position top and left

### ISSUE THREAD

**Issue by trinione** [kirkas/Ascensor.js#43]
I am seeing the new options for width and height. Can the option for top and left also be added?

I am making the change in my code but was wondering if it can also be added to the code on your end.

```
      // Setup floor size & position
      this.node.css({
        'position': 'absolute',
        'overflow': 'hidden',
        'top': '100px',
        'left': '100px',
        'width': this.options.width,
        'height': this.options.height
      });
```

I have changed to the following and added the options accordingly and it appears to work fine and not break the code any. Is this all I need to do?

```
      // Setup floor size & position
      this.node.css({
        'position': 'absolute',
        'overflow': 'hidden',
        'top': this.options.top,
        'left': this.options.left,
        'width': this.options.width,
        'height': this.options.height
      });

```

**Comment by kirkas** [comment]
it this still an issue?

**Comment by cyberic99** [comment]
I agree with @trinione , it would be great it we could set top and left options.
Or if we could restrict the ascensor to a wrapper div.
If possible, a dynamic top would be great as well.

Is there any way to do that, even if it invoves workarounds?

Thanks
