### ISSUE TITLE
Really amazing Plugin!! and How to produce the "active" text-link effect?

### ISSUE THREAD

**Issue by DecimoNono** [kirkas/Ascensor.js#53]
Hello Kirkas!! :)
Really amazing Plugin (what else can a web designer ask for??) 1. We can manage our different webpages as a full screen layout 2. We have an intuitive and easy to use navigation system and 3. the scrolling effect is fun and renders the content in an understandable way for the end user.

One thing I would like to know is regarding to the "active" link effect: when you go to some "floor" or div, you expect the corresponding text-link turns to an "active" state (changing the text color, for example).

When I use the ".links-to-floor" class method in the menu system, the corresponding script work perfectly:

    ascensor.on("scrollStart", function(event, floor){
    $(".links-to-floor a").removeClass("selected");

    $(".links-to-floor a:eq("+floor.to+")").addClass("selected");
    });

But when I try to point the link to an specific class (.example) using:

    $(".exmple").click(function() {
    ascensor.trigger("scrollToStage", 10);
    });

I have not a clue about how to produce the "active" text-link effect at the corresponding "floor" or div.

I will apreciate to much if you give me some advice on this…
Thank you very much!
And congratulation for this awsome and usefull plugin!!

**Comment by kirkas** [comment]
Hi,

Supposedly that should work! If you go on any example and past `ascensor.trigger("scrollToStage", 3);` in the console, you'll see that navigation item change as well.

to do the same for floor, just reuse the same snippet:


```js
ascensor.on("scrollStart", function(event, floor){
    // add active class to navigation item
    $(".links-to-floor a").removeClass("selected");
    $(".links-to-floor a:eq("+floor.to+")").addClass("selected");

    // Add active class to floor
    $(".floor").removeClass("selected");
    $(".floor:eq("+floor.to+")").addClass("selected");
});
```

PS: Don't forget to add the class floor to every one of your floor!
