### ISSUE TITLE
IE 9 & 10 Not Displaying Floors

### ISSUE THREAD

**Issue by jimiayler** [kirkas/Ascensor.js#57]
M. Galley -- Peace be unto you and please forgive my posting so much markup related to my issue, but it is driving me crazy and preventing my development of a new website. 

I am using your otherwise marvelous Ascensor plugin to achieve parallax scrolling on a new site and it works great…except in IE 9 10 (I won’t bother you with anything below that!). My issue is the "floors" in my attached HTML work perfectly in a media query below 1200 pixels, but above that, they do not display at all. Note all the scripts related to this HTML file load fine.

Does anything jump out at you below that I missed? Is there something unique about IE 9 and 10 which would have them display below 1200px but not above? Greatly appreciate any recommendations you might be able to provide. Thanks, j

<html>
<head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
      <meta name="viewport" content="user-scalable=0,width=device-width,initial-scale=1,maximum-scale=1">
      <title>Sample Code</title>
      
      <link href="css/bootstrap.min.css" rel="stylesheet">
      <link href="css/navbar.css" rel="stylesheet">

      <script src="scripts/jquery-2.1.1.min.js"></script>
      <script src="scripts/bootstrap.min.js"></script>

      <style>
        @media only screen and (min-width : 1200px) {
            .floor {
              display: block;
              height: 500px;
            }
            #ascensorBuilding {
              margin: 142px auto 0;
              position: relative !important;
              width: 1280px !important;
              z-index: 999;
            }
            .floor-1 {
              background-color: #0ff;
              display: block;
            }
            .floor-2 {
              background-color: #f0f;
            }
            .floor-3 {
              background-color: #ff0;
            }
            .floor-4 {
              background-color: #fff;
            }
            .floor-5 {
              background-color: #999;
            }
            .floor-6 {
              background-color: #666;
            }
            .floor-7 {
              background-color: #0ff;
            }
            .floor-8 {
              background-color: #f0f;
            }
            .floor-9 {
              background-color: #ff0;
            }
        }
        @media only screen and (max-width : 1200px) {
            #ascensorBuilding {
              margin-top: 110px;
            }
            .floor {
              height: 500px;
              width: 100%;
            }
            .floor-1 {
              background-color: #0ff;
            }
            .floor-2 {
              background-color: #f0f;
            }
            .floor-3 {
              background-color: #ff0;
            }
            .floor-4 {
              background-color: #fff;
            }
            .floor-5 {
              background-color: #999;
            }
            .floor-6 {
              background-color: #666;
            }
            .floor-7 {
              background-color: #0ff;
            }
            .floor-8 {
              background-color: #f0f;
            }
            .floor-9 {
              background-color: #ff0;
            }
          }

      </style>

</head>
<body>
        
        <div class="pagewidth">
            <div class="pagehead">
                  <div class="headcontent">
                    <div class="col-md-6 headcontain">
                      <div class="eheadtext">Gartner Application Architecture, Development &amp; Integration Summit</div>
                      <div class="eheadsubtext">25 - 26 August 2014 | Sydney, Australia</div>
                    </div><img class="headlogo" src="images/gartsummits_logo.png" />
                  </div>
               <div class="topmenu links-to-floor">
                  <ul>
                     <li class="menutext">Why Attend</li>
                     <li class="menutext">Agenda</li>
                     <li class="menutext">Speakers</li>
                     <li class="menutext">Sponsors</li>
                     <li class="menutext">Venue &amp; Travel</li>
                     <li class="menutext">Community</li>
                  </ul>
                  <div class="register">
                    <div class="dropdown">
                      <a class="regbut" data-toggle="dropdown" href="#">Register Now<span id="dropicon" class="glyphicon glyphicon-cog"></span></a>
                      <ul id="widemenu" class="dropdown-menu links-to-floor" role="menu">
                        <li><a href="#">Approval Tools</a></li>
                        <li><a href="#">Event Brochure</a></li>
                        <li><a href="#">Save the Date</a></li>
                        <li><a href="#">Social Media</a></li>
                      </ul><a class="headlogin" href="#">Attendee&nbsp;Login</a>
                    </div>
                    
                  </div>
               </div>
            </div>
            <div class="hidicon">
              <span id="respicon" class="glyphicon glyphicon-cog" data-toggle="dropdown"></span>
              <ul id="mobmenu" class="dropdown-menu" role="menu">
                        <li class="regor"><a href="#">Register Now</a></li>
                        <li class="attlog"><a href="#">Attendee&nbsp;Login</a></li>
                        <li><a href="#">Why Attend</a></li>
                        <li><a href="#">Agenda</a></li>
                        <li><a href="#">Speakers</a></li>
                        <li><a href="#">Sponsors</a></li>
                        <li><a href="#">Venue &amp; Travel</a></li>
                        <li><a href="#">Community</a></li>
                        <li><a href="#" class="subdrop">Approval Tools</a></li>
                        <li><a href="#" class="subdrop">Event Brochure</a></li>
                        <li><a href="#" class="subdrop">Save the Date</a></li>
                        <li><a href="#" class="subdrop">Social Media</a></li>
                      </ul>
            </div>
            
            <div id="ascensorBuilding">
              <div class="floor floor-1"><span class="text"><h1>Why Attend</h1></span></div>
              <div class="floor floor-2"><span class="text"><h1>Agenda</h1></span></div>
              <div class="floor floor-3"><span class="text"><h1>Speakers</h1></span></div>
              <div class="floor floor-4"><span class="text"><h1>Sponsors</h1></span></div>
              <div class="floor floor-5"><span class="text"><h1>Venue &amp; Travel</h1></span></div>
              <div class="floor floor-6"><span class="text"><h1>Community</h1></span></div>
              <div class="floor floor-7"><span class="text"><h1>Approval Tools</h1></span></div>
              <div class="floor floor-8"><span class="text"><h1>Event Brochure</h1></span></div>
              <div class="floor floor-9"><span class="text"><h1>Save the Date</span></div>
            </div>

         </div>
    <script src="scripts/jquery.ascensor.js"></script>
    <script>
      var ascensor = $('#ascensorBuilding').ascensor();
      var ascensorInstance = $('#ascensorBuilding').data('ascensor');
        
      $(".links-to-floor li").click(function(event, index) {
        var test = 
        ascensorInstance.scrollToFloor($(this).index());
      });

      $("#widemenu li").click(function(event, index) {
        ascensorInstance.scrollToFloor($(this).index()+6);
      });

      $("#mobmenu li").click(function(event, index) {
        ascensorInstance.scrollToFloor($(this).index()-2);
      });

      $(".links-to-floor li:eq("+ ascensor.data("current-floor") +")").addClass("selected");

      ascensor.on("scrollStart", function(event, floor){
        $(".links-to-floor li").removeClass("selected");
        $(".links-to-floor li:eq("+floor.to+")").addClass("selected");
      });

      $(".prev").click(function() {
        ascensorInstance.prev();
      });
        
      $(".next").click(function() {
        ascensorInstance.next();
      });
        
      $(".direction").click(function() {
        ascensorInstance.scrollToDirection($(this).data("direction"));
      }); 
    </script>

</body>
</html>

**Comment by kirkas** [comment]
Hi, sorry for the late response. Happy to know you find a solution. Next time I advice using codepen or jsfiddle!
