### ISSUE TITLE
Can you explain "queued" in its description?

### ISSUE THREAD

**Issue by koenpopma** [kirkas/Ascensor.js#61]
Can you explain where "queued" can be used for? Or what it blocks in combination with the option "loop", if it does(?)

**Comment by kirkas** [comment]
Here's the new description:

**queued**
Type: `boolean` or `string`
Default: `false`
descriptions: define queued transition.
`false`: transition will happen simultaneously for X and Y axis
`"x"`: will animate on the X axis, then on the Y
`"y"`: will animate on the Y axis, then on the X
example: `queued: 'x'`
