### ISSUE TITLE
Improve rendering

### ISSUE THREAD

**Issue by Ponyboy47** [kirkas/Ascensor.js#64]
Possible enhancement to make would be to have ascensor set all pages not currently being viewed to `display: none;`. I was having issues with a 5 page website having very choppy transitions between pages. The site was basically unusable on any mobile device and we were going to scrap ascension, but once we started setting all pages not currently viewed to `display: none;` the site began to run as smooth as butter.

**Comment by kirkas** [comment]
Mhhh the problem is that in most case, we want page in-between other page to be shown. Let's say you slide from section 1 to section 5, with this logic, there would scroll between 3 blanks pages!

I think this will be improved with #10
