### ISSUE TITLE
Prevent Tab to kick you out of current section

### ISSUE THREAD

**Issue by gabrielbrunacci** [kirkas/Ascensor.js#66]
Hey! I am working on a site which shopping cart flow use been build using your plugin, which is amazing!

I would like to know if there is a way to prevent users getting to `div#section-b` if they are on `div#section-a` by pressing `tab` without disabling `tab` key on the whole page. 

You can replicate that behavior on your site: http://kirkas.ch/ascensor/ by pressing `tab` you can get to other sections, but the menu and url don't change

Thank you!

**Comment by kirkas** [comment]
This is quite a complicate issue, I'm always against breaking default navigation pattern like tab on page. Therefor I won't implement this inside Ascensor.js, however, here's a snipped to cancel tab action on a certain element.

```
document.getElementById('IDofYourFloor').onkeydown = function(e){
    if (e.keyCode == 9) {
        return false;
    }
}
```
