### ISSUE TITLE
firefox wheelNavigation don't work

### ISSUE THREAD

**Issue by pooyaa** [kirkas/Ascensor.js#67]
hi
anyone can help to repair this issue?
wheelNavigation dont work on firefox and IE

any way to fix it?
Thanks and regards

**Comment by kirkas** [comment]
I've just pushed a new build that should fix this, could you confirm?

**Comment by pooyaa** [comment]
Hello dear friend.
It is a good decision.
Does Firefox have been fixed?
It's great that you are attempting to update it.
Thank you very much.

I'm testing soon.

**Comment by pooyaa** [comment]
Wow this is great.
It is compatible with all devices.
Thank you.
